@startuml
'skinparam classAttributeIconSize 0
'left to right direction
skinparam linetype ortho


package BL {

	package JADE {

		abstract class Agent <<Abstract, JADE>>
		abstract class Behaviour <<Abstract, JADE>>
		Behaviour -- Agent
	}

	package DataObjects{
		
		class Device {
			+name : String
			+subtype : String
			+location : String
		}

		class Sensor {
			+currState : double
			+sensingProperties : List<String>
			+change(double) : void
		}

		class Actuator {
			+actions : List<Action>
			+act(Sensors, Action) : void
		}

		class Effect {
			+property : String
			+delta : double
		}

		class Action {
			+name : String
			+powerConsumption : double
			+effects : List<Effect>
		}

		enum RelationType {
			EQ
			GEQ
			LEQ
			GT
			LT
		}

		enum Prefix {
			BEFORE
			AFTER
			AT
		}

		class Rule {
			+isActive : boolean
			+device : Device
			+property : String
			+ruleValue : double
			+prefixType : RelationType
			+relationValue : double
			+prefix : Prefix
		}

		class AgentData {
			+name : String
			+neighbors : List<AgentData>
			+backgroundLoad : double[Problem.horizon]
			+priceSchema : double[Problem.horizon]
			+houseType : int
			+rules : List<Rule>
			+actuators : List<Actuator>
			+sensors : List<Sensor>
		}

		class Problem {
			id : String
			allDevices : Map<Integer, List<Device>>
			allHomes : List<AgentData>
			horizon : int
			granularity : int
			priceScheme : double[horizon]
		}

		Device <|-- Sensor
		Device <|-- Actuator

		Actuator o-- Action
		Action o-- Effect

		Problem *-- AgentData
		AgentData o-- Sensor
		AgentData o-- Actuator
		AgentData o- AgentData
		AgentData o-- Rule

		Prefix <-- Rule
		RelationType <-- Rule
		Rule o-- Device
	}

	package Agents {

		class SmartHomeAgent {
			+agentData : agentData
			+bestIteration : AgentIterationData
			+currIteration : AgentIterationData
			+numOfIterations : int
		}

		Note "action(){\n\twhile(!stop){\n\t\t...\n\t\tdoIteration();\n\t\tsendIterationToCollector();\n\t\t..\n\t}\n}" as smabNote

		abstract class SmartHomeAgentBehaviour <<Abstract>> {
			+agent : SmartHomeAgent
			+name : String
			#{abstract} doIteration() : void
			-sendIterationToCollector(AgentIterationData) : void
			+action() : void
			+done() : boolean

		}

		class DBA {
			+doIteration() : void
		}

		class DSA {
			+doIteration() : void
		}

		class Algo3 {
			+doIteration : void
		}

		class Algo4 {
			+doIteration() : void
		}


		Agent <|-- SmartHomeAgent
		Behaviour <|-- SmartHomeAgentBehaviour
		SmartHomeAgent -- SmartHomeAgentBehaviour

		SmartHomeAgentBehaviour .. smabNote

		Problem *-- Device

		SmartHomeAgentBehaviour <|-- DBA
		SmartHomeAgentBehaviour <|-- DSA
		SmartHomeAgentBehaviour <|-- Algo3
		SmartHomeAgentBehaviour <|-- Algo4
	}

	package IterationData {

		class AgentIterationData {
			+iterNum : int
			+agentName : String
			+price : double
			+powerConsumption : double
			+powerConsumptionPerTick : double[]
		}

		class IterationCollectedData {

			+problemId : String
			+algorithm : String
		} 

		AgentIterationData <|-- IterationCollectedData
	}

	package DataCollection {

		class DataCollector {
		    +algorithmRunEnded() : void
		}

		class DataCollectionCommunicator {

		}

		class DataCollectionCommunicatorBehaviour {
			+action() : void
			+done() : boolean
		}

		class StatisticsHandler {

		}

		class IterationAvgPrice {
			+iter : int
			+avgPrice : double
		}


		class AlgorithmProblemResult {
			+problem : Problem
			+algorithm : SmartHomeAgentBehaviour
			+avgPricePerIteration : Map<int, IterationAvgPrice>
			+iterationsTillBestPrice : int
			+lowestCostInBestIteration : double
			+lowestCostInBestIterationAgentName : String
			+highestCostInWBestIteration : double
			+highestCostInWBestIterationAgentName : String
		}

		DataCollector o-- DataCollectionCommunicator
		DataCollector o-- IterationCollectedData
		DataCollectionCommunicatorBehaviour --|> Behaviour
		DataCollectionCommunicatorBehaviour --o DataCollectionCommunicator
		DataCollector --> StatisticsHandler

		SmartHomeAgent o-- AgentIterationData
		AlgorithmProblemResult o-- IterationAvgPrice
	}

	class Experiment {
		-dataCollector : DataCollector
		-problems : List<Problem>
		-algorithms : List<SmartHomeAgentBehaviour>
		-algorithmProblemRunResults : List<AlgorithmProblemResult>
		+runExperiment() : void
		+algorithmRunEnded(AlgorithmProblemResult) : void
		+stop() : void
	}

	class Service <<Observable>> {
		+createExperiment(List<Problem>, List<SmartHomeAgentBehaviour>) : boolean?
		+runExperimrent() : boolean?
		+stopExperiment() : boolean?
		+getExperimentResults() : List<AlgorithmProblemResult>
        +experimentEnded(List<AlgorithmProblemResult>)
        +saveExperimentResults(List<AlgorithmProblemResult>) : void
	}

	Service "1"--"1" Experiment
	Service --> AlgorithmProblemResult
	Experiment o-- DataCollector
	Experiment *-- Problem
	SmartHomeAgent *- AgentData
	DataCollector --> AlgorithmProblemResult : create

	Experiment o-- AlgorithmProblemResult

	DataCollectionCommunicator "1"--"1...*" SmartHomeAgentBehaviour
	DataCollectionCommunicator --> AgentIterationData
	DataCollector --> AgentIterationData
}

package PL {
	class UiHandler <<Observer>> {

	}

	class ChartViewer {

	}

	UiHandler --> ChartViewer
}

package DAL {

    interface FileSaverInterface {
    	+saveExpirimentResult(List<AlgorithmProblemResult>) : void
    }

	class ExcelHandler {
    	+saveExpirimentResult(List<AlgorithmProblemResult>) : void
	}

    interface JsonLoaderInterface {
        +loadDevices(String) : Map<int, Device>
        +loadProblem(String) : Problem
        +getAllProblemNames() : List<String>
    }

	class JsonsLoader {
		+loadDevices(String) : Map<int, Device>
		+loadProblem(String) : Problem
		+getAllProblemNames() : List<String>
	}

    interface AlgoLoaderInterface {
		+loadAlgorithms(List<String>) : SmartHomeAgentBehaviour
        +getAllAlgoNames() : List<String>
        +addAlgoToSystem(String, String) : void
    }

	class AlgorithmLoader {
		+loadAlgorithms(List<String>) : SmartHomeAgentBehaviour
        +getAllAlgoNames() : List<String>
        +addAlgoToSystem(String, String) : void
        -replaceExistingAlgorithm(SmartHomeAgentBehaviour) : void
	}

    interface DataAccessControllerInterface {
        +getProblems(List<String>) : List<Problem>
        +getAvailableAlgorithms() : List<String>
        +getAlgorithms(List<String>) : List<SmartHomeAgentBehaviour>
        +addAlgorithmToSystem(String, String) : void
        +saveExpirimentResult(List<AlgorithmProblemResult>) : void
    }

	class DataAccessController {
		+getProblems(List<String>) : List<Problem>
		+getAvailableAlgorithms() : List<String>
		+getAlgorithms(List<String>) : List<SmartHomeAgentBehaviour>
		+addAlgorithmToSystem(String, String) : void
		+saveExpirimentResult(List<AlgorithmProblemResult>) : void
	}

	DataAccessController --> AlgoLoaderInterface
	DataAccessController --> JsonLoaderInterface
	DataAccessController --> FileSaverInterface

	JsonLoaderInterface <|-- JsonsLoader
	AlgoLoaderInterface <|-- AlgorithmLoader
	DataAccessControllerInterface <|-- DataAccessController
	FileSaverInterface <|-- ExcelHandler
}


class SmartHomeAlgorithm <<Not Implemented>> {
	-doIteration() : void
}

'**********out of package connections:************
JsonsLoader --> Device : creates >
JsonsLoader -> Problem : creates >
AlgorithmLoader --> SmartHomeAgentBehaviour : creates >
DataAccessController --> Problem
DataCollectionCommunicator --|> Agent

Experiment --> DataAccessControllerInterface

ExcelHandler -> AlgorithmProblemResult : saves
Service -right-> DataAccessControllerInterface

SmartHomeAlgorithm --|> SmartHomeAgentBehaviour

UiHandler "1"--"1" Service


@enduml