@startuml
actor User as u
participant DataAccessController as DAC

activate u
activate DAC
activate ExperimentConfigurationPresenter
activate Service
activate AlgorithmLoader

u -> ExperimentConfigurationPresenter : add new algorithm
ExperimentConfigurationPresenter --> u : [opens a drag and drop dialog]
alt
    u -> ExperimentConfigurationPresenter : [algorithm's implementation file]
    note left
        user selects the file
        containing the algorithm
        implementation using the
        file explorer dialog
    end note
    ExperimentConfigurationPresenter -> Service : addAlgorithm(String : selectedFilePath, String fileName)
    Service -> DAC : addAlgorithmToSystem(String : selectedFilePath, String fileName)

    DAC -> AlgorithmLoader : addNewAlgo(String: selectedFilePath, String: fileName)

    alt algorithm successfully verified and loaded

        note right
            if there is already an algorithm
            in the system with the same name
            as the file the user chose the
            new algorithm will replace the
            current one
        end note

        Service --> ExperimentConfigurationPresenter : [success]
        ExperimentConfigurationPresenter --> u : [shows a success message]

    else the selected file did not meet the requirements of algorithm implementation

        AlgorithmLoader -> Service : [failure message, success = false]
        Service --> ExperimentConfigurationPresenter : showErrorMessage(msg: String)
        ExperimentConfigurationPresenter --> u : [shows a descriptive error message]

    end

else user canceled the file selection operation

    u -> ExperimentConfigurationPresenter : cancel
end

    ExperimentConfigurationPresenter --> u : [displays the main screen]


@enduml