@startuml
actor User as u
participant StatisticsHandler as sth
participant ExperimentResultsPresenter as resP
participant UiHandler as ui
participant CsvHandler as csv
participant ExperimentRunningPresenter as RunP

activate UiHandler
activate Service
activate resP
activate csv
activate DataAccessController



Service -> UiHandler : notifyExperimentEnded(results, probToAlgoTotalTime)

UiHandler -> sth : <<create>>
activate sth
group for each chart
    ui -> sth : <<calculateChart>>
    sth --> resP : [graph dataset]
end group

ui -> DataAccessController : saveResults(Map<String, List<Double>> totalPowerConsumption, List<AlgorithmProblemResult> experimentResults)
DataAccessController -> csv : saveExpirmentResult(List<AlgorithmProblemResult> problemResults)

ui -> RunP : [enables "Go to Results Screen" button]
u-> RunP : [clicks "Go to Results Screen" button]

RunP -> resP : [navigate to the results view]

resP -> u : [shows graphs describing the results of the experiment]

u -> resP : [clicks "End Experiment" button]

resP -> ExperimentConfigurationPresenter : [navigate to the main screen]

@enduml