@startuml
[*] -down-> LandingPage
LandingPage --> AlgorithmsLoaded : selected algorithms loaded successfully
LandingPage --> ProblemsLoaded : selected problems loaded successfully

LandingPage -left-> LandingPage : selected problems failed verification

AlgorithmsLoaded --> AlgorithmsProblemsLoaded : selected problems loaded successfully
AlgorithmsLoaded -> AlgorithmsLoaded : selected problems failed verification
ProblemsLoaded --> AlgorithmsProblemsLoaded : selected algorithms loaded successfully

AlgorithmsProblemsLoaded -> SimulationIsRunning : run simulation
SimulationIsRunning -> LandingPage : cancel simulation

SimulationIsRunning -> DisplayResults : simulation ended

DisplayResults -> LandingPage : discard results
DisplayResults -> LandingPage : save results

LandingPage -right-> LandingPage : add new algorithm

@enduml