@startuml
actor User as u
participant DataAccessController as DAC

activate u
activate DAC
activate UiHandler
activate Service
activate AlgorithmLoader

u -> UiHandler : add new algorithm
UiHandler --> u : [opens a file selection dialog]
alt
    u -> UiHandler : [algorithm's implementation file]
    note left
        user selects the file
        containing the algorithm
        implementation using the
        file explorer dialog
    end note
    UiHandler -> Service : addAlgorithm(String : selectedFilePath, String fileName)
    Service -> DAC : addAlgorithmToSystem(String : selectedFilePath, String fileName)

    alt algorithm successfully verified and loaded

        DAC -> AlgorithmLoader : addAlgoToSystem(String: selectedFilePath, String: fileName)

        opt there is already an algorithm in the system with the same name as the file the user chose
            AlgorithmLoader -> AlgorithmLoader : replaceExistingAlgorithm(SmartHomeAgentBehaviour: newAlgorithm)
        end

        Service --> UiHandler : showSuccessMsg(msg: String)
        UiHandler --> u : [shows a success message]

    else the selected file did not meet the requirements of algorithm implementation

        AlgorithmLoader -> Service : [InstantiationException or IllegalAccessException]
        Service --> UiHandler : showErrorMessage(msg: String)
        UiHandler --> u : [shows a descriptive error message]

    end

else user canceled the file selection operation

    u -> UiHandler : cancel
end

    UiHandler --> u : [displays the main screen]


@enduml