@startuml

actor user
actor system <<system>>


rectangle "add algorithm to system"{

	(add new algorithm) as (main)
	(choose algorithm file) as (choose)
	(load algorithm file) as (load)
	(process algorithm file) as (process)
	(add algorithm to system) as (addToSys)

	(error in algorithm file) as (err)
	(replace existing algorithm \n with same name) as (replace)

  	user -- (main) : selects
  	user -- (choose)
  	(load) -- system
  	(process) --system
  	(addToSys) --system
  	(replace) --system

  	(main) .left.> (choose) : includes
  	(main) .down.> (load) : includes
  	(main) .> (process) : includes
  	(main) .> (addToSys) : includes

  	(replace) .> (addToSys) : extends
  	(err) .up.> (process) : extends
}
@enduml